package med.voll.api.domain.medico;

//AL MOMENTO DE REGISTRAR UN MEDICO CON ESTA ESPECIALIDAD DEBE SER FORZOZO EN MAYUSCULAS COMO SE INDICA ABAJO
public enum Especialidad {
    ORTOPEDIA,
    CARDIOLOGIA,
    GINECOLOGIA,
    PEDIATRIA
}
